name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to ECS Fargate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIAUQ4L3FHBG7SNOF5F
          aws-secret-access-key: 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
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        env:
          ECR_REPOSITORY: wisecow-app
          IMAGE_TAG: latest
        run: |
          docker build -t wisecow-app:latest .
          docker tag wisecow-app:latest 311141542338.dkr.ecr.eu-west-1.amazonaws.com/wisecow-app:latest
          docker push 311141542338.dkr.ecr.eu-west-1.amazonaws.com/wisecow-app:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: wise-cluster
          service: wisecow-task-service-62xtzbzd
          image: 311141542338.dkr.ecr.eu-west-1.amazonaws.com/wisecow-app:latest
